name: Autograding Tests

on:
  push:
  pull_request:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: pip install pytest

    - name: Run Tests
      id: test_assignment_py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 100
        setup-command: pip install pytest

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_ASSIGNMENT_PY_RESULTS: "${{steps.test_assignment_py.outputs.result}}"
      with:
        runners: test_assignment_py
